name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v5
    - name: Build da imagem Docker
      run: |
        docker build . --fileDockerfile --tag my-image-name:$(date +%s)